# Generated by Django 5.1.3 on 2024-11-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='context_type',
            field=models.CharField(choices=[('general', 'General'), ('document_query', 'Document Query')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='is_active_query',
            field=models.BooleanField(default=False),
        ),
    ]
