# Generated by Django 5.1.3 on 2024-11-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chat_context_type_document_is_active_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='is_active_query',
            new_name='is_document_query',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='context_type',
        ),
    ]
