# Generated by Django 5.1.3 on 2024-11-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_rename_is_active_query_document_is_document_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_document_query',
            field=models.BooleanField(default=False),
        ),
    ]
