# Generated by Django 5.1.3 on 2024-11-21 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_chat_is_document_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.document'),
        ),
    ]
