# Generated by Django 5.1.3 on 2024-11-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_chat_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='document',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='is_document_query',
        ),
    ]
