# Generated by Django 5.1.3 on 2024-11-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_remove_chat_document_remove_chat_is_document_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='session_id',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
    ]
