# Generated by Django 5.1.3 on 2024-11-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_document_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_document_query',
        ),
    ]
